### ISSUE TITLE
Fails to import Money

### ISSUE THREAD

**Issue by dapicella** [MscrmTools/Javista.AttributesFactory#1]
When importing money fields I receive the following error with the standard money settings that are in the excel file: "Value was either too large or too small for an Int32."

**Comment by MscrmTools** [comment]
Ok, I thought this error was fixed. 
I will fix it tomorrow

**Comment by MscrmTools** [comment]
It’s fixed! Just update the tool in XrmToolBox

**Comment by dapicella** [comment]
Thank you it works great!

Doug Apicella
Manager, Talent Development
Solution Architect, CE

Hitachi Solutions
Direct: +1-864-404-3591
Mobile: +1-630-253-2510
dapicella@hitachisolutions.com<mailto:dapicella@hitachisolutions.com>
www.hitachi-solutions.com
