### ISSUE TITLE
Overloading IIS/CRM on-premises - causing slowdown, timeouts for users 

### ISSUE THREAD

**Issue by lammy82** [MscrmTools/Javista.AttributesFactory#10]
When creating large numbers of attributes on an on-prem CRM server, other users working in CRM experience slowdowns, time-outs, etc. IIS CPU usage is spiking and I'm not sure if there are database table locks being created on the back-end as the columns are being added to the back end. We've boosted RAM & CPU on CRM and SQL servers which seems to have helped but not eliminated the problem.

It's not always feasible to schedule entity creation for out-of-hours, so it would be really useful to have a 'throttle' option where the tool pauses for a few seconds between each attribute it processes, to allow IIS to serve other user requests and minimise these effects, at the expense of taking longer to process the spreadsheet overall.

**Comment by MscrmTools** [comment]
Hi @lammy82, I can work on this kind of throttle setting. Stay tuned

**Comment by MscrmTools** [comment]
@lammy82, a new version is available with this feature.
Please let me know if it fits your needs
