### ISSUE TITLE
Request change attribute types names to match D365

### ISSUE THREAD

**Issue by eccountable** [MscrmTools/Javista.AttributesFactory#12]
I would like to use this template to be part of my design documentation, but the nomenclature of attributes (ex: OptionSet vs Choice) is not consistent with the current version of D365. There is no chance that MS will go back to the "classic" attribute data types any time soon. Please update the tool to use the current data type names.

**Comment by MscrmTools** [comment]
You are very active on my metadata tools 😁
This is a fair request and I will work on it.

**Comment by MscrmTools** [comment]
A new version is available with this feature included
