### ISSUE TITLE
Get Template Improvement

### ISSUE THREAD

**Issue by eccountable** [MscrmTools/Javista.AttributesFactory#13]
In the Schema field, I use a formula to make it easier to just paste the Display Names
`=CONCAT("new_",SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE((SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(B3,"/","")," ",""),")","")),"(",""),"#",""),"?",""),"'",""))`
Could you include that in the base template?

**Comment by MscrmTools** [comment]
Thank you for the suggestion.
I could include part of your request but not the solution prefix which might not be known when filling the Excel spreadsheet.

**Comment by MscrmTools** [comment]
@eccountable Added in latest version to come today
