### ISSUE TITLE
Global Choice syncing not tracked

### ISSUE THREAD

**Issue by sheikx800** [MscrmTools/Javista.AttributesFactory#18]
Doesn't appear to correctly map and apply the use of global choice sync settings within Choices. Each Choice item that is exported creates a new individual global Choice object rather than mapping back to the original. 

![choiceoptionset](https://user-images.githubusercontent.com/6202849/171996515-e762472d-1bb8-473b-ba53-ffb7373b38be.png)

**Comment by MscrmTools** [comment]
@sheikx800 should be handled better in the latest release that will arrive today
