### ISSUE TITLE
Currency Precision

### ISSUE THREAD

**Issue by eccountable** [MscrmTools/Javista.AttributesFactory#23]
Steps to reproduce: I am creating a new Money field, and I make the precision to 4 in the spreadsheet (attached). I ran the Process Attributes, then the field is created and put on a form. When a user opens the form, the precision is only 2 decimals. I checked the solution UI, and the field shows 'Currency Precision' in the Precision option set, and it does allow me to change it to 4 decimal places, so I have a work around (not critical).

I am using version 1.2022.11.16 of your fantastic tool !!!!

D365 info:
Server version: 9.1.0007.0005
Client version: 1.4.3672-v91onpremise

[example currency precision.zip](https://github.com/MscrmTools/Javista.AttributesFactory/files/10012500/example.currency.precision.zip)
Thanks!

**Comment by MscrmTools** [comment]
Hi @eccountable, Thank you for reporting the issue.

I'm not handling this Money property in the current version. I will add it ASAP

**Comment by MscrmTools** [comment]
As I don't have an english based environment available, could you send me a screenshot of the available values in the maker UI? So that I can use the same wording in the template?

**Comment by MscrmTools** [comment]
Well there is too much value here and it misses one display name
