### ISSUE TITLE
Not able to create columns

### ISSUE THREAD

**Issue by dml5055** [MscrmTools/Javista.AttributesFactory#25]
Hi,

I'm not able to create new columns from the template.  I am getting the "Object reference not set to an instance of an object" error.

Current existing fields will get updated, but new columns I'm trying to create are not working.

**Comment by MscrmTools** [comment]
Is the error message general or per column to create?

**Comment by MscrmTools** [comment]
I will check this asap.
Thank you for reporting the issue
