### ISSUE TITLE
No control over schema name for generated Relationships

### ISSUE THREAD

**Issue by mattp65** [MscrmTools/Javista.AttributesFactory#27]
It would be nice to be able to optionally provide the schema name to be used when generating a relationship. The default naming gets really long with redundant prefixes and depending the schema lengths, this can max out the generated schema name resulting in an error. When creating a relationship in the UI, the schema name is limited to 45 characters and this easily exceeds this limit.

This could easily be an additional column in the template where the value is defaulted when not present.

**Comment by MscrmTools** [comment]
Maybe Microsoft lowered the max length for schéma name because I already handle max size to 100 characters which was the api limit as far as I remember. 
But yes, I can add this feature

**Comment by MscrmTools** [comment]
@mattp65 As far as I understand, as I'm limiting the schema name to 100 characters, it shouldn't fail due to the length

Maybe truncating name to 100 results in a schema name that already exists, if multiple relationships are created to the same table from the same table. Is that your case? 

I would like to see the kind of error message you get.

Again, yes, I can add the possibility to specify your own schema name but I need to understand the size limit here

**Comment by mattp65** [comment]
@MscrmTools Yeah, it's weird they use a size limit of 45 in the maker portal when it can handle 100. You can get an error if you have long schema names and the generated value exceeds the 100 chars with 2 new relationship where the difference in the generated name is after char 100 (not a likely scenario, but 'possible'). 

But this is more about the option to override that generated name (if desired) like can be done in the UI. Reality is, if you are using the Maker Portal, you end up overriding the value more often because of the 45 char limit it imposes. I also not plenty of people who just don't like the generated default values because you end up with a LOT of prefixes and many like to strip these out.  So new_new_entity1_new_entty2 could become something 'cleaner' like new_entity1_entity2.

**Comment by MscrmTools** [comment]
makes totally sense!

**Comment by MscrmTools** [comment]
Hi @mattp65 would you be able to test this new version that handles schema name for relationship?

[Javista.AttributesFactory.zip](https://github.com/MscrmTools/Javista.AttributesFactory/files/10518983/Javista.AttributesFactory.zip)

**Comment by mattp65** [comment]
@MscrmTools  Thanks for the rapid turn around. The base functionality works as expected. A few things I noticed :

- Get Template, clicking 'Yes' to open the downloaded template fails with a File Not Found error. This works fine in Export Tables.
- Export Tables should populate the relationship schema name. If the generated 'default' schema name does not match the existing relationship name in the system, it throws an error. Guessing this error would have occurred before on a relationship created via the portal where the name had to be shortened.  
The better (and more difficult) solution would be to determine the relationship based on the column name, but far easier to just populate the existing value.
- In Export Tables, the template used is not the same one that is downloaded by Get Template. The new col is there, but it includes data validation based on the cascade values.

I ran thru both create & update scenarios with a relationship with a provided schema name though and all seems to working there. Also did some checks with using the default schema name.

FYI: Oddity with the Maker Portal I noticed on this. Caching can be an issue as Updates definitely take awhile to show on the Maker Portal. Probably not a normal situation where someone would be viewing it in the Maker Portal, process an update thru this, then view the result in the Maker Portal, but it does lag.  I even saw a scenario where the new Display Name showed, but when opening the relationship, the resulting cascade changes wasn't showing yet.

**Comment by MscrmTools** [comment]
Oh yes, i forgot to populate the cell when exporting... I will review all your points.
Thank you for testing

**Comment by mattp65** [comment]
Found another small item.
`if ((info.Type == "Customer" || info.Type == "Lookup" || info.Type == "Lookup (Multi table)") && settings.AddLookupSuffix && !info.Attribute.EndsWith("Id"))`

Doesn't do the same ToLower check you use in other places.

**Comment by mattp65** [comment]
Also found this one:
`if (settings.AddOptionSetSuffix && !omd.Name.EndsWith("code"))`
