### ISSUE TITLE
Data type "Autonumber" not supported

### ISSUE THREAD

**Issue by andremusiol** [MscrmTools/Javista.AttributesFactory#28]
It would be nice if you could include the data type Autonumber as well.
![image](https://user-images.githubusercontent.com/21216028/215497696-15cdd81e-2050-477c-ad79-835f68d7ad7b.png)

**Comment by MscrmTools** [comment]
hi @andremusiol, autonumber is just a string of type Autonumber. So just create a single line of text with column Autonumber format set

**Comment by andremusiol** [comment]
I take it back, sorry I didnt see it xD
