### ISSUE TITLE
Adding functionality for formula type columns

### ISSUE THREAD

**Issue by ArneRustad** [MscrmTools/Javista.AttributesFactory#29]
Hi,

First of all, great tool, makes creating Power Apps a lot more pleasant. I was, however, wondering if you were planning to implement functionality for formula type columns in the near future?

Kind regards,
Arne

**Comment by MscrmTools** [comment]
@ArneRustad  Thank you for asking!
It seems a formula column is nothing else than a standard typed column with a formula so it should be possible. Let me do some tests to see if the api accept to create formula column.

**Comment by ArneRustad** [comment]
Great, thanks!

**Comment by MscrmTools** [comment]
@ArneRustad so it was not so complicated
I just don't know exactly what format is expected for the formula. 

For example, I created a datetime column with the formula : `createdon`. It did create the column and the formula is shown as `'Créé le'` (The display name of the column createdon in French). So it means the formula is stored in a technical way and rendered as a user friendly formula. So the technical way has to be used in the Excel template but maybe it will be different from PowerFx... I honestly don't know.

Anyway, can you try this version that implements both Import and Export with Formula support
[Javista.AttributesFactory.zip](https://github.com/MscrmTools/Javista.AttributesFactory/files/10557498/Javista.AttributesFactory.zip)

**Comment by ArneRustad** [comment]
@MscrmTools that was extremely efficient! Will definitely give it a try, but I am currently a bit lost about how to activate it. Should I merely copy-paste it somewhere or do something else?

**Comment by ArneRustad** [comment]
Fantastic, will check it out.

**Comment by ArneRustad** [comment]
Initial impression is that this works great. Currently, only initiated a single test with four new columns (all decimal, but two of them formulas). For the first formula column the formula was merely an integer, whilst for the second the formula was the two non-formula columns multiplied together (using display name, not logical name). Both were created and when added to an app, they displayed the correct behavior. They also seemed fine when I examined the dataverse column.

![image](https://user-images.githubusercontent.com/51076842/216099862-cee511ca-de70-4231-bc4c-b59884cc2970.png)

![image](https://user-images.githubusercontent.com/51076842/216100837-1d83db15-4dc0-4255-9a5d-182ab7e50347.png)

**Comment by MscrmTools** [comment]
Cool! So I guess this can be released so...

Thank you for testing

**Comment by ArneRustad** [comment]
Yeah, seems pretty close to release. Thank you very much. However, I unfortunately got an error when I tried to recreate your example.  Not sure if I recreated it correctly.

![image](https://user-images.githubusercontent.com/51076842/216104627-3683a889-9e57-4df2-b140-04cdfb2b20ad.png)

Got this error message:

![image](https://user-images.githubusercontent.com/51076842/216105308-33ded5c7-c2be-42ce-bd0a-8b9dfa3479f1.png)

When I created a datetime column with formula as UTCNow() it worked perfectly

**Comment by MscrmTools** [comment]
My sample was using the logical name, so `createdon`. This is when looking in the maker UI that I saw the result `'Créé le'` 

So it seems we need to find how to handle column with space in the display name

**Comment by ArneRustad** [comment]
Ah, I see! Then it makes sense. Tried to use the logical name instead and then I got the same result as you with it being changed to display name when checking the formula in the UI. Check with some other columns as well and seems a solution for display names with spaces is to just use the logical name. :) Thank you for a very quick solution to my problem.

**Comment by MscrmTools** [comment]
@ArneRustad you're welcome! I'm always glad to provide the latest features of the power platform in my tools!
