### ISSUE TITLE
More than one Look Up on same parent entity

### ISSUE THREAD

**Issue by ciso72** [MscrmTools/Javista.AttributesFactory#3]
Hello, i've to build an entity with 3 lookup with account as target. I've tried every combination but the add in will throw an error and only the first lookup will e created.

**Comment by MscrmTools** [comment]
Shouldn't be an issue. One point is you cannot have three lookup with parental relationship behavior. 
This is the only issue I can see that could stop you from creating them

**Comment by MscrmTools** [comment]
@ciso72 I'm talking about this part
![image](https://user-images.githubusercontent.com/10774317/84921919-65baac80-b0c5-11ea-8eb7-c99c3c2a9d4c.png)

Try to put one with behavior Parental (if needed) and the other to Referential

If you can show me the error message, I migth help more (maybe I'm totally wrong with my assumption of error cause)
