### ISSUE TITLE
Feature request for column deletion

### ISSUE THREAD

**Issue by ArneRustad** [MscrmTools/Javista.AttributesFactory#30]
Hi,

Another feature request from me in quick succession of the previous. It would be quite useful if the tool also allowed for easy deletion of columns. Until now I've been using Attribute Manager for this, but when a lot of columns are to be deleted it is both quite tedious and time consuming as you have to go through the process of doing this for every single one of them.

My initial thought would be to add another choice to the Action column (add "Delete" or something in addition to "Ignore" and "Process"). This would match very well with the already included export functionality of the tool, where we could just export the table information to Excel and then quickly select action "Delete" for those columns we want removed.

Is this something that would be difficult to implement?

Kind regards,
Arne

**Comment by MscrmTools** [comment]
It should take at least 10 minutes to implement 😆 
But it would be just hard try to delete the attribute. If the attribute is referenced somewhere (form, view, plugin, etc.) the deletion will fail.

**Comment by ArneRustad** [comment]
Haha, sounds good! Even just deletion of unreferenced attributes is very useful. I can imagine that deletion of columns that are referenced somewhere (as done in the Attribute manager tool) is a quite complex procedure, but would of course be even more useful.
