### ISSUE TITLE
Missing table detected but table exists

### ISSUE THREAD

**Issue by andremusiol** [MscrmTools/Javista.AttributesFactory#32]
With the newest version i receive the following error about a missing table:
![image](https://user-images.githubusercontent.com/21216028/218167267-3e051e3b-7c0b-48f2-8507-bc0be106b4a5.png)

Source file looks like this, only one row set to "Progress":
![image](https://user-images.githubusercontent.com/21216028/218167680-145c78eb-e2e2-49c4-99c2-1aed4fc11b3b.png)

But the table already exists in the selected solution:
![image](https://user-images.githubusercontent.com/21216028/218168462-24649469-3e2b-415e-833f-4f35701e3e1a.png)
![image](https://user-images.githubusercontent.com/21216028/218167858-6150b0cf-fd2c-48d1-9c9d-9821f727b521.png)

What am I doing wrong here? 🤔
In the end I just want to update the values of a choice column.

**Comment by MscrmTools** [comment]
Oh! I know what I made wrong...

Fixing it right now

**Comment by MscrmTools** [comment]
Fix is on its way for release
