### ISSUE TITLE
Export Table: Object reference not set to an instance

### ISSUE THREAD

**Issue by dave-buckley-valto** [MscrmTools/Javista.AttributesFactory#40]
Hi, when trying to export some tables, I get the below error:

![image](https://github.com/MscrmTools/Javista.AttributesFactory/assets/101286354/aacdff8a-bcf9-435c-84bf-b9db5d13637b)

Is there a workaround / solution for this? Or am I missing something? Some tables seem to work fine.

**Comment by MscrmTools** [comment]
I never experienced it before and I'm using it quite a lot...

Can you filter down to a specific table that would produce this error? if so, anything specific? Do you try to export system and deribed columns too?

**Comment by dave-buckley-valto** [comment]
Hi, thanks for getting back so quick.

Note that the tables we are exporting are on-premise tables (if that makes any difference). I am doing tables one at a time, it appears to occur on some tables but not others, haven't tried multiple at once.

I have tried exporting it with a combination of no system, derived, system and derives etc, but no luck. I'll provide a more comprehensive guide on how I produce the error.

I also don't get anything in the logs as it is failing on export, not during.

**Comment by PatrickGaul** [comment]
I and a colleague are having exactly the same issue, same plugin version (1.2023.2.33), same circumstances attempting to export tables from an on-premise Dynamics environment. **_Microsoft Dynamics 365 Version 1612 (8.2.24.14) (DB 8.2.28.11) on-premises_**

**Comment by dave-buckley-valto** [comment]
@PatrickGaul While attempting to debug further, I found that uninstalling version 1.2023.2.33 and installing the previous version (1.2023.2.32), the issue was no longer present

**Comment by MscrmTools** [comment]
tagging @dave-buckley-valto, @PatrickGaul

**Comment by PatrickGaul** [comment]
It works now!  Thanks for the fix!
