### ISSUE TITLE
Problems with calculated fields

### ISSUE THREAD

**Issue by romeusantiago** [MscrmTools/Javista.AttributesFactory#5]
Hi guys! How are you? Hope you're fine! ;)

So I'm using the tool to create a calculated field but even filling the excel sheet correctly, the new field is created "bugged".

Instead of the new attribute have the "Calculated" field type it was created with the "Simple" one.

Please check the prints.

Could u help me, please!?

Tks in advance.

![image](https://user-images.githubusercontent.com/15317054/101874206-36ae6080-3b67-11eb-977e-8c239f996732.png)

![image](https://user-images.githubusercontent.com/15317054/101874336-7e34ec80-3b67-11eb-9ed8-86257367f15a.png)

**Comment by MscrmTools** [comment]
Hi @romeusantiago, congrats! you found a bug!
I'm fixing it right now and will be pushing a new version soon after

**Comment by romeusantiago** [comment]
Thanks and best regards, my friend! ;)

**Comment by romeusantiago** [comment]
Guys, now I'm getting an error during the process.

Check it out:

![image](https://user-images.githubusercontent.com/15317054/101964299-aff19600-3bef-11eb-8ea2-fe4f5151d091.png)

![image](https://user-images.githubusercontent.com/15317054/101964349-d7e0f980-3bef-11eb-9da6-d98bf5ce310d.png)


I've uploaded the error screen and the Excel sheet print.

**Comment by MscrmTools** [comment]
This is because the attribute was created as simple and cannot be modified to calculated.
Can you delete the attribute before using the tool to recreate it ?

**Comment by romeusantiago** [comment]
Hi guys! I've deleted and recreated and it works. Thank u so much! ;)
