### ISSUE TITLE
Updating the Existing Global OptionSet Attribute Failed

### ISSUE THREAD

**Issue by LinnZawWin** [MscrmTools/Javista.AttributesFactory#6]
_Steps to repro_
1. Export the existing columns into Excel
2. Update the display name of the existing OptionSet attribute with "Is Global" = Yes and change the Action for that row to Process
3. Select the Excel file and click Process

_Expected Result_
The display name of the OptionSet is updated

_Actual Result_
The process failed with "Could not find an option set with the specified name: xyz_OptionSetAttributeLogicalName"

![image](https://user-images.githubusercontent.com/14156926/134019596-39997979-bdfd-4501-8adf-c0d8d654df87.png)

**Comment by MscrmTools** [comment]
Thank you @LinnZawWin! I think the issue is that optionset names are always lower case.
Shouldn't be too hard to fix then

**Comment by MscrmTools** [comment]
@LinnZawWin can you check with this version?

[Javista.AttributesFactory.zip](https://github.com/MscrmTools/Javista.AttributesFactory/files/7197289/Javista.AttributesFactory.zip)

**Comment by MscrmTools** [comment]
Was the custom option set attribute created with this tool or not?
I guess I maybe cannot determine the name of the global optionset based on the name of the pick list attribute.
Can you tell me what is the name of the global optionset?

**Comment by LinnZawWin** [comment]
The custom option set attribute was created manually in the maker portal and the tool was used just to bulk update the Display Name of the attributes. (adding prefix to 200+ fields)
The name of the global optionset is "custom_yesornoorblank"

I don't think the tool needs to know or even action based on the name of the global optionset for the Update of the attribute. For Update of the optionset attribute, the users cannot possibly change any properties other than the following ones. The rest of the Excel column values can be ignored for updating the existing optionset attribute
- Display name
- Description
- Required level
- Valid for advanced find
- Field secured
- Enabled for audit
- Default Value

**Comment by MscrmTools** [comment]
New version to test. This one retrieve the global optionset name of the existing attribute. That should work better
[Javista.AttributesFactory.zip](https://github.com/MscrmTools/Javista.AttributesFactory/files/7201203/Javista.AttributesFactory.zip)

**Comment by LinnZawWin** [comment]
@MscrmTools Awesome. I have tested this version and it is working fine to update the Display Name of the existing global option set. Please proceed to close this issue with the next release.

**Comment by MscrmTools** [comment]
great! thanks for confirming the issue is resolved!
