### ISSUE TITLE
How can I create a field with two options and set the value because I can't find a place to set it in the template

### ISSUE THREAD

**Issue by FrankZhu1020** [MscrmTools/Javista.AttributesFactory#8]
Hi MscrmTools！
How can I create a field with two options and set the value because I can't find a place to set it in the template

**Comment by MscrmTools** [comment]
@FrankZhu1020 , This way

![image](https://user-images.githubusercontent.com/10774317/155280379-3377210c-ec51-409d-8344-dbe30c0f95de.png)
