### ISSUE TITLE
Create entities/tables

### ISSUE THREAD

**Issue by FrankZhu1020** [MscrmTools/Javista.AttributesFactory#9]
Hi MscrmTools！
Whether it is possible to create the corresponding entity according to a sheet table, and can automatically create the entity！This makes it easy to manage and maintain. @MscrmTools

**Comment by MscrmTools** [comment]
Hi, that is technically possible but would need more work than what I can do these days.

**Comment by FrankZhu1020** [comment]
Hi MscrmTools！
Thanks for the reply, it would be great if it technically works and you have plans for an update！

**Comment by MscrmTools** [comment]
Implemented in latest version
